### ISSUE TITLE
HttpError: Network request for 'getMe' failed

### ISSUE THREAD

**Issue by phuctm97** [grammyjs/grammY#475]
I'm running grammY on AWS Lambda via AWS API Gateway and keep getting this error.

![image](https://github.com/grammyjs/grammY/assets/25026967/c3660fa9-595a-4ce6-a06f-558c6394868b)

Appreciate any pointers.

PS: It worked perfectly with Telegraf before, I'm migrating from Telegraf to grammY.

**Comment by KnorpelSenf** [comment]
Fixed in https://t.me/grammyjs/158379

**Comment by dannylin108** [comment]
Still have this issue, **grammy 1.19.1**

`bot.start()` cause this errors in console:

```
grammy:bot Initializing bot +0ms
  grammy:core Calling getMe +0ms
  grammy:core Calling deleteWebhook +45ms
  grammy:error HttpError: Network request for 'getMe' failed!
  grammy:error     at /<...>/node_modules/.pnpm/grammy@1.19.1/node_modules/grammy/out/core/error.js:74:15
  grammy:error     at processTicksAndRejections (node:internal/process/task_queues:95:5)
  grammy:error     at runNextTicks (node:internal/process/task_queues:64:3)
  grammy:error     at listOnTimeout (node:internal/timers:540:9)
  grammy:error     at process.processTimers (node:internal/timers:514:7)
  grammy:error     at async ApiClient.call (/<...>/node_modules/.pnpm/grammy@1.19.1/node_modules/grammy/out/core/client.js:54:29)
  grammy:error     at async ApiClient.callApi (/<...>/node_modules/.pnpm/grammy@1.19.1/node_modules/grammy/out/core/client.js:84:22)
  grammy:error     at async withRetries (/<...>/node_modules/.pnpm/grammy@1.19.1/node_modules/grammy/out/bot.js:485:41)
  grammy:error     at async Bot.init (/<...>/node_modules/.pnpm/grammy@1.19.1/node_modules/grammy/out/bot.js:154:22)
  grammy:error     at async Promise.all (index 0) +0ms```

**Comment by KnorpelSenf** [comment]
If this is the same issue, then the same solution will work. If it's a new and unrelated issue, please open a new issue with a minimal reproduction example.
